// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProviderStuff.Data.Data;

#nullable disable

namespace ProviderStuff.Data.Migrations
{
    [DbContext(typeof(ProviderStuffDbContext))]
    [Migration("20260901193554_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProviderStuff.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ProviderStuff.Domain.Entities.ContactPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ContactPoints");
                });

            modelBuilder.Entity("ProviderStuff.Domain.Entities.MonitoredAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("PingIntervalSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("MonitoredAddresses");
                });

            modelBuilder.Entity("ProviderStuff.Domain.Entities.PingResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<Guid>("MonitoredAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredAddressId", "Timestamp");

                    b.ToTable("PingResults");
                });

            modelBuilder.Entity("ProviderStuff.Domain.Entities.StatusChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MonitoredAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredAddressId");

                    b.ToTable("StatusChangeLogs");
                });

            modelBuilder.Entity("ProviderStuff.Domain.Entities.ContactPoint", b =>
                {
                    b.HasOne("ProviderStuff.Domain.Entities.Client", "Client")
                        .WithMany("ContactPoints")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ProviderStuff.Domain.Entities.MonitoredAddress", b =>
                {
                    b.HasOne("ProviderStuff.Domain.Entities.Client", "Client")
                        .WithMany("MonitoredAddresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ProviderStuff.Domain.Entities.PingResult", b =>
                {
                    b.HasOne("ProviderStuff.Domain.Entities.MonitoredAddress", "MonitoredAddress")
                        .WithMany("PingResults")
                        .HasForeignKey("MonitoredAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredAddress");
                });

            modelBuilder.Entity("ProviderStuff.Domain.Entities.StatusChangeLog", b =>
                {
                    b.HasOne("ProviderStuff.Domain.Entities.MonitoredAddress", "MonitoredAddress")
                        .WithMany("StatusChangeLogs")
                        .HasForeignKey("MonitoredAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredAddress");
                });

            modelBuilder.Entity("ProviderStuff.Domain.Entities.Client", b =>
                {
                    b.Navigation("ContactPoints");

                    b.Navigation("MonitoredAddresses");
                });

            modelBuilder.Entity("ProviderStuff.Domain.Entities.MonitoredAddress", b =>
                {
                    b.Navigation("PingResults");

                    b.Navigation("StatusChangeLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
